services:
  app:
    build: .
    ports:
      - "8090:3000"
    container_name: polosimapp
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://web-api.polosim.com/api/V1/
