export interface Product {
  id: string;
  name: string;
  description: string;
  priceInCents: number;
  flag: string;
  data: string;
  validity: string;
  speed: string;
  bestSeller?: boolean;
  region?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "turkey-10gb",
    name: "Turkey",
    description: "10GB Data Plan for Turkey",
    priceInCents: 1499,
    flag: "🇹🇷",
    data: "10GB",
    validity: "30 Days",
    speed: "4G/LTE",
    bestSeller: true,
    region: "europe",
  },
  {
    id: "europe-20gb",
    name: "Europe",
    description: "20GB Data Plan for 40+ European Countries",
    priceInCents: 2999,
    flag: "🇪🇺",
    data: "20GB",
    validity: "30 Days",
    speed: "4G/LTE",
    bestSeller: true,
    region: "europe",
  },
  {
    id: "japan-15gb",
    name: "Japan",
    description: "15GB Data Plan for Japan",
    priceInCents: 2499,
    flag: "🇯🇵",
    data: "15GB",
    validity: "30 Days",
    speed: "5G/4G",
    bestSeller: true,
    region: "asia",
  },
  {
    id: "usa-30gb",
    name: "USA",
    description: "30GB Data Plan for United States",
    priceInCents: 3499,
    flag: "🇺🇸",
    data: "30GB",
    validity: "30 Days",
    speed: "5G/4G",
    bestSeller: false,
    region: "americas",
  },
  {
    id: "thailand-8gb",
    name: "Thailand",
    description: "8GB Data Plan for Thailand",
    priceInCents: 1199,
    flag: "🇹🇭",
    data: "8GB",
    validity: "15 Days",
    speed: "4G/LTE",
    bestSeller: false,
    region: "asia",
  },
  {
    id: "australia-25gb",
    name: "Australia",
    description: "25GB Data Plan for Australia",
    priceInCents: 3999,
    flag: "🇦🇺",
    data: "25GB",
    validity: "30 Days",
    speed: "5G/4G",
    bestSeller: false,
    region: "oceania",
  },
  {
    id: "uk-12gb",
    name: "UK",
    description: "12GB Data Plan for United Kingdom",
    priceInCents: 1999,
    flag: "🇬🇧",
    data: "12GB",
    validity: "30 Days",
    speed: "5G/4G",
    bestSeller: true,
    region: "europe",
  },
  {
    id: "korea-10gb",
    name: "South Korea",
    description: "10GB Data Plan for South Korea",
    priceInCents: 1899,
    flag: "🇰🇷",
    data: "10GB",
    validity: "30 Days",
    speed: "5G/4G",
    bestSeller: false,
    region: "asia",
  },
  {
    id: "germany-15gb",
    name: "Germany",
    description: "15GB Data Plan for Germany",
    priceInCents: 2299,
    flag: "🇩🇪",
    data: "15GB",
    validity: "30 Days",
    speed: "5G/4G",
    bestSeller: false,
    region: "europe",
  },
  {
    id: "france-12gb",
    name: "France",
    description: "12GB Data Plan for France",
    priceInCents: 1999,
    flag: "🇫🇷",
    data: "12GB",
    validity: "30 Days",
    speed: "5G/4G",
    bestSeller: false,
    region: "europe",
  },
  {
    id: "uae-10gb",
    name: "UAE",
    description: "10GB Data Plan for United Arab Emirates",
    priceInCents: 2199,
    flag: "🇦🇪",
    data: "10GB",
    validity: "30 Days",
    speed: "5G/4G",
    bestSeller: false,
    region: "middle-east",
  },
  {
    id: "singapore-12gb",
    name: "Singapore",
    description: "12GB Data Plan for Singapore",
    priceInCents: 1999,
    flag: "🇸🇬",
    data: "12GB",
    validity: "30 Days",
    speed: "5G/4G",
    bestSeller: false,
    region: "asia",
  },
];
